import type { VideogameInterface } from '@/interfaces/VideogameInterface';

export const videogameSeeder: VideogameInterface[] = [
  {
    id: 1,
    name: 'The Witcher 3',
    genre: 'RPG',
    description: 'Open world RPG with deep storytelling.',
    online: false,
    price: 39.99,
    imageUrl: 'witcher3.jpg',
    totalSales: 50000000,
    releaseYear: 2015,
    director: 'Konrad Tomaszkiewicz',
    studioId: 1,
  },
  {
    id: 2,
    name: 'GTA V',
    genre: 'Action',
    description: 'Open world crime action game.',
    online: true,
    price: 29.99,
    imageUrl: 'gtav.jpg',
    totalSales: 180000000,
    releaseYear: 2013,
    director: 'Leslie Benzies',
    studioId: 2,
  },
  {
    id: 3,
    name: 'Zelda: Breath of the Wild',
    genre: 'Adventure',
    description: 'Open world adventure game.',
    online: false,
    price: 59.99,
    imageUrl: 'zelda_botw.jpg',
    totalSales: 31000000,
    releaseYear: 2017,
    director: 'Hidemaro Fujibayashi',
    studioId: 3,
  },
];
